/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInferface;

import MainModel.StudentClass;
import MainModel.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dipenpatel
 */
public class StudentDetailsAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentDetailsAdminJPanel
     */
//    public StudentDetailsAdminJPanel() {
//        initComponents();
//    }
    private JPanel WorkArea;
    private StudentDirectory StudentDirectory;
    private StudentClass StudentClass;
    
    StudentDetailsAdminJPanel(JPanel WorkArea,StudentDirectory StudentDirectory) {
        initComponents();
        this.WorkArea=WorkArea;
        this.StudentDirectory=StudentDirectory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jStudentDetails = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnDetailDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(186, 79, 84));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Details");

        jStudentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "NEU ID", "Course"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jStudentDetails);
        if (jStudentDetails.getColumnModel().getColumnCount() > 0) {
            jStudentDetails.getColumnModel().getColumn(0).setResizable(false);
            jStudentDetails.getColumnModel().getColumn(1).setResizable(false);
            jStudentDetails.getColumnModel().getColumn(2).setResizable(false);
            jStudentDetails.getColumnModel().getColumn(3).setResizable(false);
        }

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDetailDetails.setText("Delete Details");
        btnDetailDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnViewDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetailDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnViewDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetailDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        WorkArea.remove(this);
        CardLayout layout=(CardLayout) WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDetailDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow=jStudentDetails.getSelectedRow();
        if(selectedRow>=0){
            int dialogButton=JOptionPane.YES_NO_OPTION;
            int dialogResult=JOptionPane.showConfirmDialog(null, "Would you like to delete this row","Warning",dialogButton);
            if(dialogResult==JOptionPane.YES_OPTION){
                StudentClass studentclass=(StudentClass) jStudentDetails.getValueAt(selectedRow, 0);
                StudentDirectory.deleteStudent(studentclass);
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Select the Row","Warring",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDetailDetailsActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int SelectedRow=jStudentDetails.getSelectedRow();
        if(SelectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select the row","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            StudentClass studentclass=(StudentClass) jStudentDetails.getValueAt(SelectedRow, 0);
            
            adminStudentViewDetailsJPanel adminstudentviewdetailsjpanel=new adminStudentViewDetailsJPanel(WorkArea,StudentDirectory,studentclass);
            WorkArea.add("adminStudentViewDetailsJPanel",adminstudentviewdetailsjpanel);
            CardLayout layout=(CardLayout) WorkArea.getLayout();
            layout.next(WorkArea);
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetailDetails;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jStudentDetails;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

     DefaultTableModel dtm=(DefaultTableModel) jStudentDetails.getModel();
     dtm.setNumRows(0);
     for(StudentClass StudentClass:StudentDirectory.getStudentList()){
         Object[] row=new Object[4];
         row[0]=StudentClass;
         row[1]=StudentClass.getLastName();
         row[2]=StudentClass.getNEUID();
         row[3]=StudentClass.getUserID();
         dtm.addRow(row);
     }
    }
}
